# Generated by Django 5.0 on 2024-01-03 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_servingsizeoption_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servingsizeoption',
            name='servingSizeFood',
        ),
        migrations.AddField(
            model_name='servingsizeoption',
            name='food',
            field=models.ForeignKey(default= "71a9e805-de6d-42da-ad20-f4173c54ed8c", on_delete=django.db.models.deletion.CASCADE, related_name='servingSizeOptions', to='base.food'),
            preserve_default=False,
        ),
    ]
