# Generated by Django 5.0 on 2024-01-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_food_consumetime_remove_food_servingsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='base.food'),
        ),
    ]
