# Generated by Django 5.0 on 2024-01-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_entry_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='numServings',
            new_name='numServing',
        ),
    ]
