# Generated by Django 5.0 on 2024-01-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_numservings_entry_numserving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='consumeTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
